export {default as Dashboard} from "./Dashboard/Dashboard"
export {default as Sites} from "./Sites/Sites"
export {default as Ubicacion} from "./Ubicaciones/Ubicacion" 
export {default as Feeders} from "./Feeders/Feeders" 
export {default as Login } from "./auth/Login"